### ISSUE TITLE
USER STORY: Challenge 'LOVE RUNNING' submit answer to the poll

### ISSUE THREAD

**Issue by AMJL-16** [AMJL-16/my-first-agile-project#3]
In order to **provide an answer or an opinion to the topic** as a **user**, I can **choose an answer from the poll**

# Acceptance Criteria:

* The answer options should be  provided as checkboxes and submit button
* The checkbox should be "checked" by default

# Tasks 

- [ ] Include the checkbox and to show the name of the submitter using HTML and CSS
- [ ] Create a new field to track the username 
- [ ] Test the functionality
