### ISSUE TITLE
USER STORY: POLLS AND ADMINISTRATOR

### ISSUE THREAD

**Issue by AMJL-16** [AMJL-16/my-first-agile-project#4]
In order to **keep anonymous vote** as a **the administrator**, I can **add votes and keep record of older polls**

# Acceptance Criteria

* The  user should have a checkbox option to be anonymous or not
* This checkbox should be next to the submit button 
* The administrator should have a private input box to erase or add votes

# Tasks
- [ ] Include the checkbox 
- [ ] Update the layout using HTML and CSS
- [ ] Add the input for the administrator
- [ ] Test the functionality
